### ISSUE TITLE
Json decimal throws exception

### ISSUE THREAD

**Issue by mechjman** [aloneguid/config#82]
Hi team, when using a decimal for a value I get the following exception:

`Unhandled Exception: System.NotSupportedException: type System.Decimal on object 'PaymentAmount' is not supported.
   at Config.Net.Core.Box.BoxFactory.ValidateSupportedType(ResultBox rb, ValueHandler valueHandler)
   at Config.Net.Core.Box.BoxFactory.DiscoverProperties(Type t, ValueHandler valueHandler, Dictionary`2 result, String base
Path)
   at Config.Net.Core.Box.BoxFactory.Discover(Type t, ValueHandler valueHandler, String basePath)
   at Config.Net.Core.InterfaceInterceptor..ctor(Type interfaceType, IoHandler ioHandler, String prefix)
   at Config.Net.ConfigurationBuilder`1.Build()
`
I've tested with this with Newtonsoft.Json dependency and it works fine.

**Comment by mikefoxnobel** [comment]
More basic types are supported.
Version updated on 2018-10-16, please try new version.
